### ISSUE TITLE
Any plan to merge the outstanding PR(s)?

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/gglasso-feedstock#3]
### Comment:

Hey @Vlasovets, I see that there are two outstanding PRs for this repo that have not been merged in quite some time.  In addition, at least for the 0.2.0 PR, the dependencies are out of sync with the upstream repo.  Do you have any plan to merge either or both of these PRs?

**Comment by Vlasovets** [comment]
hey @DManowitz ,
thanks for the heads up, I've just merged the PRs.
